# Sequence of Mappings, one mapping per node
---
global:
  override:
    network:
      dns:
        - 8.8.8.8
        - 8.8.4.4
  flannel:
    network_range: 10.2.0.0/16
  k8s:
    master_host: k8s-master.example.org
    service_ip_range: 10.3.0.0/24
    service_ip: 10.3.0.1
    dns_service_ip: 10.3.0.10
  versions:
    hyperkube: v1.4.5_coreos.0
    calico: latest
    policy_controller: v0.5.0
    leader_elector: v0.1.0
    coreos_release: "stable"
  sdef:
    domain: sdef.example.org
    cf_apikey: aaa111222333
    cf_email: mail@example.org

nodes:
-
  hostname: k8s-master.example.org
  network:
    ip: 172.1.0.2
    subnet: 24
    gateway: 172.1.0.1
  etcd:
    nodename: node1
  k8s:
    isworker: false
  includes:
    key_inc: keys.yml
    misc_inc: misc.yml
    k8s: k8s-master.tmpl
-
  hostname: k8s-worker.example.org
  network:
    ip: 172.254.0.2
    subnet: 24
    gateway: 172.254.0.1
  etcd:
    nodename: node1
  k8s:
    isworker: true
  includes:
    key_inc: keys.yml
    misc_inc: misc.yml
    k8s: k8s-worker.tmpl
